version: '3'

services:
  wordpress-app:
    image: wyveo/nginx-php-fpm:latest
    ports:
      - "8081:80"
    volumes:
      - ./:/usr/share/nginx/html
    depends_on:
      - wordpress-db

  wordpress-db:
    image: mariadb:10.3
    command:  "--character-set-server=utf8 --collation-server=utf8_general_ci --innodb-use-native-aio=0"
    restart: "no"
    ports:
      - "8082:3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_ROOT_HOST: "%"

  wordpress-adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8083:8080
    depends_on:
      - wordpress-db