version: '3'

services:
  wordpress-nginx:
    build: ./.docker/nginx
    restart: "no"
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - wordpress-app

  wordpress-app:
    build: .
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www
    depends_on:
      - wordpress-db
      - wordpress-adminer

  wordpress-db:
    image: mariadb:10.3
    command:  "--character-set-server=utf8 --collation-server=utf8_general_ci --innodb-use-native-aio=0"
    restart: "no"
    ports:
      - "8001:3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_ROOT_HOST: "%"

  wordpress-adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8002:8080
    depends_on:
      - wordpress-db